(1-2)初級 入力値エラー処理
hayashiasu/ex-emp-management-bugfix pull request #2
Opened 2023-02-17 07:17 UTC by hayashiasu

上記の機能を追加しました。
レビューをお願い致します。

問題があればコメントをお願い致します。
特に問題がなければマージをお願い致します。

2023-02-17 08:06 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2023-02-17 08:06 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
> +		redirectAttributes.addFlashAttribute("administrator", administrator);
この1行は不要です。次の画面に表示するものではないため。

2023-02-17 08:06 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
> +		return "redirect:/administrator/login";
口頭でおお伝えしたとおりログイン画面に戻らないので修正をお願いします。

2023-02-17 08:14 UTC, hayashiasu commented
ご指摘いただいた点を修正いたしました。
再度レビューをお願い致します。

2023-02-17 09:48 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

次回からで良いので、１改修１ブランチで作成をお願いします。
(今回は1-4の改修も含まれているようでした)

2023-02-17 09:48 UTC, merged

2023-02-20 04:14 UTC, hayashiasu commented
申し訳ございません。
ブランチの作成方法、次回より気をつけます。
ご確認ありがとうございました。