(1-3)中級 Eメール重複チェック
hayashiasu/ex-emp-management-bugfix pull request #6
Opened 2023-02-20 06:13 UTC by hayashiasu

上記の改修が完了したため、レビューをお願い致します。
※viewのinsertでのメッセージ文の挿入に自信がないので、異なる記述の方がよければご教示いただけますと幸いです。

問題があれば、その旨をコメントに記載をお願い致します。
特に問題がなければ、マージをお願い致します。

2023-02-20 07:07 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2023-02-20 07:07 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
> +			model.addAttribute("registeredAdministrator", registeredAdministrator);
この1行は不要です。削除をお願いします。

2023-02-20 07:07 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
> +			model.addAttribute("registeredMessage", "すでに登録されているメールアドレスです");
　今回のエラーメッセージの登録ですが、
　model.addAttribute("キー", "エラーメッセージ");
　ではなく、resultにエラーメッセージを追加することができます。
　このようにすると、viewでは
　「○○を入力してください」
　というformのvalidateエラーが出る箇所に、今回のものと共通でエラーメッセージを出すことができます。
　BindingResultのAPIマニュアルを見ながら探してみてください。

2023-02-20 08:49 UTC, hayashiasu commented
コメントいただいた通り改修いたしましたので再レビューをお願い致します。

2023-02-20 10:12 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2023-02-20 10:12 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
> +		System.out.println("toInsertの中のform:" + form);
間違い探し(デバッグ)で使用したこのような行はpush前に削除しましょう。

2023-02-21 00:07 UTC, hayashiasu commented
中途半端な状態でのpush作業となり大変申し訳ございません。
ご指摘いただきました箇所を修正いたしましたので再レビューをお願い致します。

2023-02-21 00:17 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

以下の回答もれていました。

>※viewのinsertでのメッセージ文の挿入に自信がないので、異なる記述の方がよければご教示いただけますと幸いです。

「メールアドレスを入力してください or すでに登録されているメールアドレスです」

の部分を指しているかと思いますが、こちらはMockで使用する文言で実際はエラーメッセージで置き換わる部分になります。
そのため、どちらかが出る形になるため、この部分の記述はどのような形でも問題ありません。

2023-02-21 00:17 UTC, merged